import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

String _appTheme = "primary";

/// Helper class for managing themes and colors.
class ThemeHelper {
  // A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme
  };

  /// Changes the app theme to [_newTheme].
  void changeTheme(String _newTheme) {
    _appTheme = _newTheme;
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.whiteA700,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          disabledBackgroundColor: appTheme.whiteA700,
          backgroundColor: appTheme.teal700,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10.h),
          ),
          shadowColor: colorScheme.primary,
          elevation: 4,
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: 18.fSize,
          fontFamily: 'League Spartan',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: 14.fSize,
          fontFamily: 'League Spartan',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.whiteA700,
          fontSize: 12.fSize,
          fontFamily: 'League Spartan',
          fontWeight: FontWeight.w400,
        ),
        headlineLarge: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 32.fSize,
          fontFamily: 'League Spartan',
          fontWeight: FontWeight.w400,
        ),
        titleLarge: TextStyle(
          color: colorScheme.primary.withOpacity(1),
          fontSize: 20.fSize,
          fontFamily: 'League Spartan',
          fontWeight: FontWeight.w400,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0X3F000000),
    primaryContainer: Color(0XFF003B25),
    secondary: Color(0XFF003B25),
    secondaryContainer: Color(0XFF85B6FF),
    tertiary: Color(0XFF003B25),
    tertiaryContainer: Color(0XFF85B6FF),

    // Background colors
    background: Color(0XFF003B25),

    // Surface colors
    surface: Color(0XFF003B25),
    surfaceTint: Color(0XFF003B25),
    surfaceVariant: Color(0XFF85B6FF),

    // Error colors
    error: Color(0XFF003B25),
    errorContainer: Color(0XFF85B6FF),
    onError: Color(0X3F000000),
    onErrorContainer: Color(0XFF003B25),

    // On colors(text colors)
    onBackground: Color(0X3F000000),
    onInverseSurface: Color(0X3F000000),
    onPrimary: Color(0XFF003B25),
    onPrimaryContainer: Color(0X3F000000),
    onSecondary: Color(0X3F000000),
    onSecondaryContainer: Color(0XFF003B25),
    onTertiary: Color(0X3F000000),
    onTertiaryContainer: Color(0XFF003B25),

    // Other colors
    outline: Color(0XFF003B25),
    outlineVariant: Color(0XFF003B25),
    scrim: Color(0XFF003B25),
    shadow: Color(0XFF003B25),

    // Inverse colors
    inversePrimary: Color(0XFF003B25),
    inverseSurface: Color(0XFF003B25),

    // Pending colors
    onSurface: Color(0X3F000000),
    onSurfaceVariant: Color(0XFF003B25),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // BlueGray
  Color get blueGray100 => Color(0XFFD9D9D9);
  Color get blueGray400 => Color(0XFF888888);
  Color get blueGray500 => Color(0XFF5D917D);
  Color get blueGray900 => Color(0XFF26342F);

  // Cyan
  Color get cyan800 => Color(0XFF067790);

  // DeepOrange
  Color get deepOrange600 => Color(0XFFF24E1E);
  Color get deepOrange800 => Color(0XFFBF6D2F);
  Color get deepOrange900 => Color(0XFF904806);

  // Gray
  Color get gray50 => Color(0XFFF8F8F8);
  Color get gray700 => Color(0XFF666666);

  // Orange
  Color get orange300 => Color(0XFFE3AD66);

  // Teal
  Color get teal400 => Color(0XFF26A375);
  Color get teal700 => Color(0XFF06905C);
  Color get teal70001 => Color(0XFF06905D);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
